describe('empty spec', () => {
    it('passes', () => {
      cy.visit('https://jpetstore.tricentis.com/jpetstore/actions/Catalog.action')
      cy.contains(/sign.in/i).click()
      cy.get('input[name="username"]').type('j2ee')
      cy.get('input[name="password"]').clear().type('j2ee')
      cy.get('input[name="signon"]').click()
      cy.get('#WelcomeContent').should('contain', 'Welcome ABC!')
      cy.get('div#SidebarContent a').eq(2).click()
      cy.get('div[id="Catalog"] h2').should('contain','Cats')
      cy.get('table tbody tr:nth-child(3) td a').click()
      cy.get('div[id="Catalog"]').should('contain', 'Persian')
      cy.get('div#Catalog table tbody tr:nth-child(2) td:nth-child(5) a').should('contain','Add to Cart').click()
      cy.get('div[id="Cart"] h2').should('contain', 'Shopping Cart')
      cy.get('a[href="/jpetstore/actions/Order.action?newOrderForm="]').should('contain', 'Proceed to Checkout').click()
      cy.get('input[name="newOrder"]').should('contain', 'Continue').click()
      cy.get('a[href="/jpetstore/actions/Order.action?newOrder=&confirmed=true"]').should('contain', 'Confirm').click()
      cy.get('div#Content ul li').should('contain', 'Thank you, your order has been submitted.')
    })
  })